name: Warehouse Automation

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Libraries
        run: pip install pandas

      - name: Run Script
        run: python warehouse.py
